#lang pollen

◊(define-meta title "If I am not for myself, then who will be for me?"
              template "../template.html.p" 
              published "Saturday, 20 April 2019"
              excerpt (list ""))

◊h1{If I am not for myself, then who will be for me?}

A contractarian account of ethics holds that morality is the name we give to the rules of human conduct which would arise if rational parties deliberated what rules would best serve to protect people’s fundamental interests. A worthy concern with this approach arises when we consider how atypical bargainers fit into this picture. For example, while contractarianism may provide good protections for healthy, normal adults, very young children, very weak people, and those gripped by physical or mental illness cannot be considered typical, rational arbiters, and so may not have a seat at the bargaining table. In this paper, I will first explicate this objection in detail, before defending a Hobbesian contractarian account of morality by demonstrating how persons excluded from bargaining would still be afforded sufficient protections in a contractarian bargain.

As articulated by Hobbes in ◊em{Leviathan}, contractarianism is a moral theory which contends that what we think of as morality is nothing more than the name we give to the rules which we would, if given the opportunity, agree upon after bargaining to protect our own self-interests. Under Hobbesian contractarianism, rational and capable bargainers will seek to protect themselves and, by extension their property, from harm by others, and in turn agree to refrain from harming others. This type of ◊em{quid pro quo} arrangement serves as the basis for the rules of human conduct which collectively form morality. The collection of rules and our collective responsibility to adhere to such rules forms the social contract we have with one another and with society as a whole. This mutual tolerance for one another’s well-being is what allows humanity to ascend above a state of constant war amongst ourselves.

The foundation for this tolerance, however, seems to be contingent on the rationality and capability of the bargainers. While such persons could conceivably come to an agreement, a person so gripped by mental illness so as to be incapable of rationality surely could not. After all, if we agree to not kill or harm one another out of a recognition that it is in our best interest to do so, then someone who cannot be reasoned with cannot be made to accept this conclusion, or even be made to recognize it in the first place. In a disturbing way, it would appear as though the contractarian bargainer must consider the insane to be no more included in the social contract than wild animals. This not only presents a concern that there may be persons who are not afforded their say in the rules, but also that they may not have any protections at all. So it goes for the mentally ill, so too it goes for small children, who are too young to be effective agents on their own behalf. The physically disabled and weakened too have little guarantee of representation on their behalf, and future generations will not be party to any decisions made today. In this regard, one may reasonably worry that Hobbesian contractarianism may exclude too many people from the protections and obligations of morality.

In defense of contractarianism against this objection, I will combine two tools which the contractarian has at his or her disposal: a veil of ignorance, and the universalization of protections. The veil of ignorance contends that when making decisions about moral issues, one should not consider who they are in the process. Without knowledge of your own position, wealth, gender, age, and so forth, the most logical decision is to appropriate protections and benefits fairly regardless of these qualities, since this affords you the smallest chance that you will be harmed by the rules put in place. Since bargainers have the incentive to make the social contract more preferable than the alternative to the greatest number of people [1], the veil of ignorance is not only a useful way to achieve what seems to be the most equitable outcomes, but also a logical choice for rational arbiters. Thus even if bargainers are not themselves children, or mentally ill, or physically handicapped, it is still in their best interest to afford these and other groups the same protections as are afforded to the healthy and capable.

One may object to the veil of ignorance as a panacea to inequity since it is reasonable to conclude that there are some personal qualities which cannot be obscured by the veil. Even though we may not know who we are behind the veil, we can certainly tell that we are bargaining, which ought to indicate that we are at least capable of complex, rational thought. Moreover, the fact that we have even considered such counterarguments suggests that we are rather good at arguing, which perhaps indicates something about our level of education or metal acuity. Because these deductions can be made from behind a veil of ignorance, it cannot be assumed that a self-interested bargainer would or should advocate on the behalf of anyone who is not in a similar position to them. This rather throws a wrench into the contractarian’s defense of the social contract. The contractarian, however, may recover at least some of the protections for persons excluded from bargaining by noting that even if one does grant that a bargainer may still known some information about themself, there is no guarantee that this is their permanent condition. Even the strong and capable can become weak and dependent through age and accident, and so it is still very much in the interest of bargainers to be impartial towards the less capable. Thus for personal qualities which are unknown behind the veil, and for those knowable qualities which are impermanent throughout life, the contractarian may be assured that they will be afforded the same protections as the most adept and rational bargainers.

There are, of course, still cases which cannot be solved so easily. While the veil of ignorance may still protect the elderly who cannot function, since bargainers will know that in time they will be old as well, it does nothing to protect young children, since a bargainer will never grow to be young and helpless. Similarly, future generations will never be the direct concern of those alive today since they cannot be the same persons. To account for these people who would otherwise be excluded from morality, the contractarian can consider that the protections and responsibilities offered by the social contract can be successively generalized to encompass more than just the bargainers. Consider, for instance, that the prohibition on harm extends beyond the physical persons of the bargainers to their property and food. This extension is possible by virtue of the fact that if it were otherwise, the contract itself would hold little weight — what good is the guarantee that others will not literally kill you to take your food if they will steal it nonetheless and leave you to starve? Since the very purpose of the social contract is to ameliorate this kind of situation, it can be reasonably known that the protections of the contract are more expansive that just the bargainers themselves; at the very least, they extend to the things the bargainers value.

This generalization of protection can be pushed beyond possessions, though, to include people who are not able to bargain on their own behalf. Consider the case of children too young to be considered able to advocate for themselves. Although there is no utility that they can provide for adults who are bargaining for them while they are children, they can and will certainly provide benefit to adults in terms of future aid, when the parents may be old and dependent on their children for help, and in terms of the intrinsic value that children have to their parents. [2] Since children are in some sense valued by adults, they too are beneficiaries of the protections offered by the social contract. One may object to this argument by noting that there are often children who are apparently not valued by their parents, or not valued by their parents as much as they ought [3] to be. For that matter, there are many young children who do not have parents, or are estranged from them. These cases present a ◊em{prima facie} refutation of the protections offered to children since, in the absence of parents the protections wouldn’t apply. However, this overlooks the fact that it need not be the children’s parents who value them, but anyone in society who values them intrinsically. There is nothing special about the parent-child relationship which grants children protections; in fact, children are not the only people who can be protected in this way. So long as one is valued by others, one is protected by the bargainers’ contract. This notion of value allows the contractarian to generalize the protections of the social contract far beyond its original arbiters. [4]

Still, one may worry that this too closely binds morality to value. After all, it seems like the cases where people are valued by others are the easiest and least problematic cases for contractarianism to deal with. Real trouble arises when we consider people who are not valued by others. If by morality we mean a refrain from harming others, and if the only people granted these protections are those valued by some in society, then it would follow that it is not immoral to harm or kill those whom society does not value, so long as they are not able to bargain for themselves. A contractarian’s answer to this lies again in the understanding of why the social contract exists in the first place; rational bargainers can understand that we are better off when we have mutual tolerance for the interests of others. Of key importance is that the ‘interests of others’ need not be restricted to the interests of other ◊em{rational bargainers} to be beneficial for society. Indeed, although some members of society could conceivably be both unable to participate in the contract and unvalued by society, this does not imply that turning a blind or even cruel eye to their self-interests is beneficial; in fact, it will be actively harmful. Consider that the original motivations for humans in the state of nature to kill one another was out of desire for food, or comfort, or safety. If these needs were already met, there would be little need to enter into the contract in the first place. Although the state of nature cannot provide this, a society bound together by a social contract can in fact provide for the welfare of those excluded from the contract. In doing so, it avoids the treat of harm from members of society who cannot participate in the contact, since there is no motivation for those people to attempt to harm others.

Contractarianism holds that morality is a description of the rules which rational bargainers would adhere to in order to protect their collective self-interests. A natural objection to this view arises out of consideration for those who are necessarily excluded from this social contract, and would then ◊em{prima facie} seem to have no rights or protections. However, by applying both a veil of ignorance and a successively generalized consideration for why protections are valuable to bargainers, contractarianism can successfully refute this critique.

◊valediction{◊p{ 
  ◊string->symbol{mdash} Jackson Petty ◊br{}
  April 2019 ◊br{}
  New Haven, CT
}}

◊section{References}
◊items[#:class "feed"]{
  ◊item{Hobbes, Thomas. ◊em{Leviathan}. 1651. Print.}
}

◊section{Notes}
◊sequence{
  ◊item{A key observation of social contract theory is that although a few well-off people may be stronger than any other person, they are not stronger than every other person put together. The same dynamics which incentivize the alliances of people to protect their group interests also incentivize rational bargainers to include as many other such bargainers in the contact.}
  ◊item{This may be a somewhat controversial position to just assume. I think, however, that it is justified for at least two reasons. Firstly, it seems rather evident in most cases that adults do value their children, and so it seems that regardless of the underlying motive that adults have for this, it is reasonable to suppose that it usually exists. Secondly, we have already seen that contractarianism provides protection for other things that people value, and so it follows easily that this protection is extended to people that other people value.}
  ◊item{Saying “as much as they ought to be” is somewhat in limbo since this whole discussion is about what the definition of ‘ought’ really is, but by this I just mean that some may feel like parents may undervalue children relatively to the value that they would place on children, were they to have any.}
  ◊item{This also justifies why parent’s cannot harm their own children. When the parents are not the sole moral guardians of children, or when children are not the sole guardians of sick adults, the less capable are still given protections from those who should act in their best interests, but perhaps do not.}
}